 # Water warm
- platform: mqtt
  name: WaterHeater Current
  state_topic: "tele/water-warm/SENSOR"
  value_template: "{{ value_json['ENERGY'].Current }}"
  unit_of_measurement: "A"
  icon: mdi:current-ac

- platform: mqtt
  name: WaterHeater Power
  state_topic: "tele/water-warm/SENSOR"
  value_template: "{{ value_json['ENERGY'].Power }}"
  unit_of_measurement: "W"
  icon: mdi:power-plug

- platform: mqtt
  name: WaterHeater Voltage
  state_topic: "tele/water-warm/SENSOR"
  value_template: "{{ value_json['ENERGY'].Voltage }}"
  unit_of_measurement: "V"
  icon: mdi:flash

- platform: mqtt
  name: WaterHeater yesterday
  state_topic: "tele/water-warm/SENSOR"
  value_template: "{{ value_json['ENERGY'].Yesterday }}"
  unit_of_measurement: "W"
  icon: mdi:power-plug

- platform: mqtt
  name: WaterHeater today
  state_topic: "tele/water-warm/SENSOR"
  value_template: "{{ value_json['ENERGY'].Today }}"
  unit_of_measurement: "W"
  icon: mdi:power-plug

- platform: mqtt
  name: WaterHeater total
  state_topic: "tele/water-warm/SENSOR"
  value_template: "{{ value_json['ENERGY'].Total }}"
  unit_of_measurement: "kWh"
