- platform: "mqtt"
  state_topic: !secret zigbee2mqtt_cube
  name: Cube
  availability_topic: "zigbee2mqtt/bridge/state"
  icon: "mdi:gesture-double-tap"
  value_template: "{{ value_json.action }}"

- platform: "mqtt"
  state_topic: !secret zigbee2mqtt_cube
  name: Cube battery
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  device_class: "battery"
  value_template: "{{ value_json.battery }}"

- platform: "mqtt"
  state_topic: !secret zigbee2mqtt_cube
  name: Cube lqi
  availability_topic: "zigbee2mqtt/bridge/state"
  icon: "mdi:signal"
  unit_of_measurement: "lqi"
  value_template: "{{ value_json.linkquality }}"