# Door sensor 1
- platform: "mqtt"
  name: Hall Door Sensor battery
  state_topic: !secret zigbee2mqtt_door1
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  device_class: "battery"
  value_template: "{{ value_json.battery }}"

- platform: "mqtt"
  name: Hall Door Sensor linkquality
  state_topic: !secret zigbee2mqtt_door1
  availability_topic: "zigbee2mqtt/bridge/state"
  icon: "mdi:signal"
  unit_of_measurement: "lqi"
  value_template: "{{ value_json.linkquality }}"