  # Home
- platform: mqtt
  name: Home Current
  state_topic: "tele/home/SENSOR"
  value_template: "{{ value_json['ENERGY'].Current }}"
  unit_of_measurement: "A"
  icon: mdi:current-ac

- platform: mqtt
  name: Home Power
  state_topic: "tele/home/SENSOR"
  value_template: "{{ value_json['ENERGY'].Power }}"
  unit_of_measurement: "W"
  icon: mdi:power-plug

- platform: mqtt
  name: Home Voltage
  state_topic: "tele/home/SENSOR"
  value_template: "{{ value_json['ENERGY'].Voltage }}"
  unit_of_measurement: "V"
  icon: mdi:flash

- platform: mqtt
  name: Home yesterday
  state_topic: "tele/home/SENSOR"
  value_template: "{{ value_json['ENERGY'].Yesterday }}"
  unit_of_measurement: "W"
  icon: mdi:power-plug

- platform: mqtt
  name: Home today
  state_topic: "tele/home/SENSOR"
  value_template: "{{ value_json['ENERGY'].Today }}"
  unit_of_measurement: "W"
  icon: mdi:power-plug

- platform: mqtt
  name: Home total
  state_topic: "tele/home/SENSOR"
  value_template: "{{ value_json['ENERGY'].Total }}"
  unit_of_measurement: "kWh"
  icon: mdi:power-plug