# Motion sensor office
- platform: "mqtt"
  name: Xiaomi Motion Sensor office illuminance
  state_topic: !secret zigbee2mqtt_motion_office
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "V"
  device_class: "voltage"
  value_template: "{{ value_json.voltage }}"

- platform: "mqtt"
  name: Xiaomi Motion Sensor office battery
  state_topic: !secret zigbee2mqtt_motion_office
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  device_class: "battery"
  value_template: "{{ value_json.battery }}"

- platform: "mqtt"
  name: Xiaomi Motion Sensor office linkquality
  state_topic: !secret zigbee2mqtt_motion_office
  availability_topic: "zigbee2mqtt/bridge/state"
  icon: "mdi:signal"
  unit_of_measurement: "lqi"
  value_template: "{{ value_json.linkquality }}"