
- platform: template
  sensors:
    battery_joaquin_redmi:
      friendly_name: Redmi Battery
      unit_of_measurement: "%"
      value_template: '{{ state_attr("device_tracker.redmi_note_8_pro","battery_level") }}'
      device_class: battery
      icon_template: >-
        {% set battery_level = state_attr("device_tracker.redmi_note_8_pro","battery_level")|int('unknown') %}
        {% set battery_round = (battery_level|int / 10)|int * 10 %}
        {% if battery_level == 'unknown' %}
          mdi:battery-unknown
        {% else %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}
        {% endif %}
    outside_temperature:
      friendly_name: Outside temperature
      unit_of_measurement: "°C"
      value_template: '{{ states("sensor.dark_sky_temperature") }}'
      icon_template: "mdi:thermometer"
    outside_humidity:
      friendly_name: Outside humidity
      unit_of_measurement: "%"
      value_template: '{{ states("sensor.dark_sky_humidity") }}'
      icon_template: "mdi:water-percent"
    last_day_of_month:
      friendly_name: Last day of current month
      value_template:  >-
        {% if now().month in [1,3,5,7,8,10,12] %}
          31
        {% elif now().month in [4,6,9,11] %}
          30
        {% elif now().month == 2 and ((now().year-2000) % 4 > 0) %}
          28
        {% elif now().month == 2 and ((now().year-2000) % 4 == 0) %}
          29
        {% endif %}
      icon_template: "mdi:calendar"
    month_energy_estimation:
      friendly_name: Month energy estimation
      value_template: "{{ (states.sensor.monthly_home_energy.state | int / now().day * states('sensor.last_day_of_month') | int) | round(2) }}"
      unit_of_measurement: "kWh"
      icon_template: "mdi:power-plug"
