homeassistant:
  name: Home
  allowlist_external_dirs:
    - /tmp
  customize: !include customize.yaml

  customize_glob:
    "sensor.dark_sky*":
      hidden: true

  auth_providers:
    - type: legacy_api_password
      api_password: !secret http_password
    - type: trusted_networks
      trusted_networks:
        - 192.168.0.0/24
        - 192.168.31.0/24
    - type: homeassistant

recorder:
  db_url: !secret recorder_db_url

# SmartIR
smartir:
  update_branch: rc

# CLIMATE
climate:
  - platform: smartir
    name: Air conditioner
    unique_id: air_conditioner
    device_code: 1382
    controller_data: remote.rm_mini_remote
    temperature_sensor: sensor.mi_t_582d3433871b
    humidity_sensor: sensor.mi_h_582d3433871b
    power_sensor: binary_sensor.ac_power

panel_iframe:
  networkmap:
    title: "Zigbee Map"
    url: "/local/community/zigbee2mqtt_networkmap/map.html"
    icon: "mdi:graphql"

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# IFTTT
ifttt:
  key: !secret ifttt_key

# Weather
weather:
  - platform: darksky
    api_key: !secret darksky_apikey

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
device_tracker:
  # - platform: bluetooth_tracker
  - platform: bluetooth_le_tracker
  - platform: xiaomi
    host: !secret router_ip
    password: !secret router_password
    interval_seconds: 30
    new_device_defaults:
      track_new_devices: false

# Telegram
telegram_bot:
  platform: polling
  api_key: !secret telegram_bot_key
  allowed_chat_ids:
    - !secret telegram_bot_chat_ids

notify:
  - name: Telegram
    platform: telegram
    api_key: !secret telegram_bot_key
    chat_id: !secret telegram_bot_chat_ids

# Text to speech
tts:
  - platform: google_translate

camera:
  - platform: ffmpeg
    name: Living room 3
    input: !secret yi_cam_input
  - platform: generic
    name: Tablet
    still_image_url: !secret tablet_still_image_url

webhook:
# ZIGBEE2MQTT
zigbee2mqtt_networkmap:

# SHOPPING LIST
shopping_list:

# GOOGLE ASSISTANT
google_assistant:
  project_id: !secret google_assistant_project_id
  exposed_domains:
    - switch
    - light
    - climate
  entity_config:
    group.all_automations:
      expose: false

# HOMEKIT
homekit:
- filter:
    include_domains:
      - switch
      - light
      - climate

### CLOUD ###
cloud:
  alexa:
    filter:
      exclude_domains:
        - automation
        - scripts
        - groups
        - binary_sensor
        - input_boolean
  google_actions:
    filter:
      exclude_domains:
        - automation
        - scripts
        - groups
        - binary_sensor
        - input_boolean

utility_meter:
  monthly_home_energy:
    source: sensor.home_total
    cycle: monthly
  weekly_home_energy:
    source: sensor.home_total
    cycle: weekly
  daily_home_energy:
    source: sensor.home_total
    cycle: daily
  daily_heater_energy:
    source: sensor.heater_total
    cycle: daily
  daily_waterheater_energy:
    source: sensor.waterheater_total
    cycle: daily
  daily_refrigerator_energy:
    source: sensor.refrigerator_total
    cycle: daily

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

vacuum:
  platform: miio2
  name: Living room
  host: !secret vacuum_host
  token: !secret vacuum_token

rest_command:
  kiosk_command:
    url: !secret rest_url_kiosk_command

# SPOTCAST
spotcast:
  sp_dc: !secret spotcast_sp_dc
  sp_key: !secret spotcast_sp_key

# SPOTIFY
spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

### INCLUDES ###

# INPUTS
input_boolean: !include inputs/input_boolean.yaml
input_datetime: !include inputs/input_datetime.yaml
input_number: !include inputs/input_number.yaml
input_select: !include inputs/input_select.yaml
input_text: !include inputs/input_text.yaml
# API
api: !include api.yaml
# TIMERS
timer: !include timers.yaml
# ALARM
alarm_control_panel: !include alarm.yaml
# INFLUXDB
#influxdb: !include influxdb.yaml
# GROUPS
group: !include groups.yaml
# LIGHTS
light: !include_dir_merge_list lights
# AUTOMATIONS
automation: !include_dir_merge_list automations
# SCRIPTS
script: !include_dir_merge_named scripts
# SWITCHES
switch: !include_dir_merge_list switches
# BINARY SENSORS
binary_sensor: !include_dir_merge_list binary_sensors
# SENSORS
sensor: !include_dir_merge_list sensors
# ZONES
zone: !include zones.yaml
# SCENES
scene: !include scenes.yaml
# COVERS
cover: !include covers.yaml
# FRONTEND
frontend:
  themes: !include_dir_merge_named themes
