  - platform: template
    sensors:
      alarm:
        friendly_name: "Alarm"
        value_template: >-
          {{ not is_state('alarm_control_panel.ha_alarm', 'disarmed') }}
        icon_template: >-
          {% if not is_state('alarm_control_panel.ha_alarm', 'disarmed') %}
            mdi:alarm-light
          {% else %}
            mdi:alarm-light-outline
          {% endif %}
          
      livingroom_tv_power:
        friendly_name: Livingroom TV Power
        icon_template: >
          {% if is_state('binary_sensor.tv_status','on') %} mdi:television
          {% else %} mdi:television-off
          {% endif %}
        device_class: power
        value_template: >-
          {% if not is_state('binary_sensor.tv_status', 'off') %}
            true
          {% endif %}

      alarm_clock:
        friendly_name: "Alarm clock active"
        value_template: >-
          {{ is_state('input_boolean.alarm_weekday', 'on') 
          and (strptime(states('sensor.date_time'),'%Y-%m-%d, %H:%M').weekday() == 0 or strptime(states('sensor.date_time'),'%Y-%m-%d, %H:%M').weekday() == 1 or strptime(states('sensor.date_time'),'%Y-%m-%d, %H:%M').weekday() == 2 or strptime(states('sensor.date_time'),'%Y-%m-%d, %H:%M').weekday() == 3 or strptime(states('sensor.date_time'),'%Y-%m-%d, %H:%M').weekday() == 4) 
          or is_state('input_boolean.alarm_weekend', 'on') 
          and (strptime(states('sensor.date_time'),'%Y-%m-%d, %H:%M').weekday() == 5 or strptime(states('sensor.date_time'),'%Y-%m-%d, %H:%M').weekday() == 6) }}
      bt_stuck:
        friendly_name: "BT"
        value_template: >-
          {% set btvalues = [
            states.sensor.mi_t_582d3433871b.last_updated,
            states.sensor.mi_h_582d3433871b.last_updated]%}
          {{ (as_timestamp(now())-as_timestamp(btvalues | max)) > 120 }}
        device_class: problem
        icon_template: >-
          {% if is_state("binary_sensor.bt_stuck", True) %}
            mdi:bluetooth-off
          {% else %}
            mdi:bluetooth
          {% endif %}
      last_day_of_the_month:
        friendly_name: 'Last Day of the Month'
        icon_template: "mdi:calendar"
        value_template: "{{ (as_timestamp(now()) + 86400)|timestamp_custom('%d', true) == '01' }}"
        