  - platform: "mqtt"
    name: Xiaomi Door Sensor
    state_topic: !secret zigbee2mqtt_door1
    availability_topic: "zigbee2mqtt/bridge/state"
    payload_on: false
    payload_off: true
    value_template: "{{ value_json.contact }}"
    device_class: "door"
  
  # Hall motion sensor
  - platform: mqtt
    name: Motion Hall
    state_topic: "stat/hall-light/PIR"
    payload_on: "1"
    payload_off: "0"
    device_class: motion